[project]
name = "network-speed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"psycopg2-binary",
	"schedule",
	"speedtest-cli",
]

[project.optional-dependencies]
dev = [
	"pytest",
]

[tool.pytest.ini_options]
pythonpath = [
	"src",
]
